//go:build darwin
// +build darwin

package keyboard

var keyNameMap = map[string]mmKeyCode{
	Backspace: mmKeyBackspace,
	Delete:    mmKeyDelete,
	Enter:     mmKeyReturn,
	Tab:       mmKeyTab,
	Esc:       mmKeyEscape,
	Up:        mmKeyUp,
	Down:      mmKeyDown,
	Right:     mmKeyRight,
	Left:      mmKeyLeft,
	Home:      mmKeyHome,
	End:       mmKeyEnd,
	Pageup:    mmKeyPageUp,
	Pagedown:  mmKeyPageDown,
	//
	F1:  mmKeyF1,
	F2:  mmKeyF2,
	F3:  mmKeyF3,
	F4:  mmKeyF4,
	F5:  mmKeyF5,
	F6:  mmKeyF6,
	F7:  mmKeyF7,
	F8:  mmKeyF8,
	F9:  mmKeyF9,
	F10: mmKeyF10,
	F11: mmKeyF11,
	F12: mmKeyF12,
	F13: mmKeyF13,
	F14: mmKeyF14,
	F15: mmKeyF15,
	F16: mmKeyF16,
	F17: mmKeyF17,
	F18: mmKeyF18,
	F19: mmKeyF19,
	F20: mmKeyF20,
	F21: mmKeyF21,
	F22: mmKeyF22,
	F23: mmKeyF23,
	F24: mmKeyF24,
	//
	Cmd:      mmKeyMeta,
	Lcmd:     mmKeyLMeta,
	Rcmd:     mmKeyRMeta,
	Alt:      mmKeyAlt,
	Lalt:     mmKeyLAlt,
	Ralt:     mmKeyRAlt,
	Ctrl:     mmKeyControl,
	Lctrl:    mmKeyLControl,
	Rctrl:    mmKeyRControl,
	Shift:    mmKeyShift,
	Lshift:   mmKeyLShift,
	Rshift:   mmKeyRShift,
	Capslock: mmKeyCapsLock,
	Space:    mmKeySpace,
	Print:    mmKeyPrint,
	Insert:   mmKeyInsert,
	Menu:     mmKeyMenu,

	AudioMute:    mmKeyAudioMute,
	AudioVolDown: mmKeyAudioDown,
	AudioVolUp:   mmKeyAudioUp,
	AudioPlay:    mmKeyAudioPlay,
	AudioStop:    mmKeyAudioStop,
	AudioPause:   mmKeyAudioPause,
	AudioPrev:    mmKeyAudioPrev,
	AudioNext:    mmKeyAudioNext,
	AudioRewind:  mmKeyAudioRew,
	AudioForward: mmKeyAudioFwd,
	AudioRepeat:  mmKeyAudioRep,
	AudioRandom:  mmKeyAudioRand,

	Num0:    mmKeyNum0,
	Num1:    mmKeyNum1,
	Num2:    mmKeyNum2,
	Num3:    mmKeyNum3,
	Num4:    mmKeyNum4,
	Num5:    mmKeyNum5,
	Num6:    mmKeyNum6,
	Num7:    mmKeyNum7,
	Num8:    mmKeyNum8,
	Num9:    mmKeyNum9,
	NumLock: mmKeyNumLock,
	//
	NumDecimal: mmKeyNumDecimal,
	NumPlus:    mmKeyNumPlus,
	NumMinus:   mmKeyNumMinus,
	NumMul:     mmKeyNumMul,
	NumDiv:     mmKeyNumDiv,
	NumClear:   mmKeyNumClear,
	NumEnter:   mmKeyNumEnter,
	NumEqual:   mmKeyNumEqual,

	LightsMonUp:     mmKeyMonUp,
	LightsMonDown:   mmKeyMonDown,
	LightsKbdToggle: mmKeyKbdToggle,
	LightsKbdUp:     mmKeyKbdUp,
	LightsKbdDown:   mmKeyKbdDown,
}
